### ISSUE TITLE
Log in not working.

### ISSUE THREAD

**Issue by parmeetdx** [dahlb/ha_kia_hyundai#159] opened 2024-08-06 16:50 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**
Hyundai Palisade USA

**Describe the bug**
Log-in is not proceeding. Even trying after logging out and logging in on the mobile app.

**Debug logs if an error occurred**

Outlined here: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.m

**To Reproduce**
1. Go t o integrations and select Kia/Hyundai. 
2. Enter login info
3.  Error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dahlb** [comment] 2024-08-07 00:40
duplicate of https://github.com/dahlb/ha_kia_hyundai/issues/83

**Closed by dahlb** 2024-08-07 00:40 UTC
