### ISSUE TITLE
won't load

### ISSUE THREAD

**Issue by wystewart** [dahlb/ha_kia_hyundai#85] opened 2023-07-15 13:57 UTC
has been able to load for several months.  this is for canada.

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ha_kia_hyundai/__init__.py", line 214, in async_setup_entry
    api_cloud_instance = api_cloud_class(
                         ^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by dahlb** [comment] 2023-07-16 00:13
this is a duplicate of https://github.com/dahlb/ha_kia_hyundai/issues/73

**Closed by dahlb** 2023-07-16 00:13 UTC
