### ISSUE TITLE
Unable to Lock/Unlock Car

### ISSUE THREAD

**Issue by 0bmay** [dahlb/ha_kia_hyundai#66] opened 2023-02-10 17:50 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**

**Describe the bug**
When I clock the lock/unlock toggle switch in Home Assistant I get the following error:
Failed to call service lock/lock. Lock.async_lock() got an unexpected keyword argument 'entity_id'

**Debug logs if an error occurred**

Outlined here: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.m

Nothing reflected in the logs

**To Reproduce**
Click on the Lock toggle switch in HA and the pop up appears

**Expected behavior**
Car to lock and unlock

**Screenshots**
![Screenshot 2023-02-10 at 9 41 49 AM](https://user-images.githubusercontent.com/57501269/218159882-1bba5a7e-8d72-43da-b2be-8e3b42e8ca98.png)

**Additional context**
Not 100% sure this is a ha_kia_hyundai issue or home assistant issue.. but I believe it started after the 2023.2.0 release..

**Comment by dahlb** [comment] 2023-02-12 19:10
thanks for writing up this detailed error report, I think it is fixed in the linked commit.  It was caused by a change in ha with a deprecation warning.  

fixed in 1.7.2

**Closed** 2023-02-12 19:15 UTC
Labels: bug

**Comment by 0bmay** [comment] 2023-02-12 19:31
Thank you! I will test when I get back home. Your addon to HA has given me so much. I love that I can auto lock my car at night and auto start the climate when its cold to go pickup up my kid from school. 👍🏼
