### ISSUE TITLE
error: SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED - unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by 0bmay** [dahlb/ha_kia_hyundai#153] opened 2024-07-22 20:00 UTC
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.md
**Region and Brand of car**
US - Kia Soul EV 2018

**Describe the bug**
Module no longer loads in HA has the following error in the log file:
error during setup: Cannot connect to host api.owners.kia.com:443 ssl:<ssl.SSLContext object at 0x7f298bfa8050> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000)], waiting 1 minute and trying again.

**Debug logs if an error occurred**
2024-07-22 12:49:26.107 DEBUG (MainThread) [custom_components.ha_kia_hyundai.api_cloud_util] US KIA in use
2024-07-22 12:49:26.145 DEBUG (MainThread) [kia_hyundai_api.us_kia] sending https://api.owners.kia.com/apigw/v1/prof/authUser request with {'deviceKey': '', 'deviceType': 2, 'userCredential': {'userId': '***', 'password': '***'}}
2024-07-22 12:49:26.275 WARNING (MainThread) [custom_components.ha_kia_hyundai] error during setup: Cannot connect to host api.owners.kia.com:443 ssl:<ssl.SSLContext object at 0x7f298bfa8050> [[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1000)], waiting 1 minute and trying again.

Outlined here: https://github.com/dahlb/ha_kia_hyundai/blob/master/README.m

**To Reproduce**
1. Start HA
2. See error

**Expected behavior**
plugin loads and gets dat for the car..

**Screenshots**

**Additional context**

**Comment by dahlb** [comment] 2024-07-22 20:05
Looks like a platform issue, https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled you might have luck following the directions in this thread.

**Comment by 0bmay** [comment] 2024-07-22 20:38
running HA inside of docker... made the openssl.conf point the docker environment to use the new config file and I'm still getting the error..
![Capto_Capture 2024-07-22_01-37-10_PM](https://github.com/user-attachments/assets/a765c90a-6b49-4c39-98bd-7091994a10d0)
Dunno what to do now..

**Comment by mrkcrc** [comment] 2024-07-22 22:03
Just advising that I am now receiving the same error message as 0bmay.  I upgraded to HA Core 2024.7.3 and after reboot the KIA integration failed to load with error: SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED - unsafe legacy renegotiation disabled.

**Comment by dahlb** [comment] 2024-07-22 22:10
thanks for filing this bug, and for chiming in @mrkcrc with your HA version information I was able to reproduce this error and will be able to work on fixing it now

**Comment by dahlb** [comment] 2024-07-23 02:05
fixed with https://github.com/dahlb/kia_hyundai_api/commit/c378e13ec3507947e95f26f8c8ac202fd7a48277 released in version 1.8.13

**Closed** 2024-07-23 02:07 UTC
Labels: bug

**Comment by 0bmay** [comment] 2024-07-23 02:12
Thank you!
